# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: div.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'div.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdiv.proto\x12\x03\x64iv\"\"\n\nDivRequest\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\"\x1a\n\x08\x44ivReply\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\x35\n\nDivService\x12\'\n\x05\x44oDiv\x12\x0f.div.DivRequest\x1a\r.div.DivReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'div_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIVREQUEST']._serialized_start=18
  _globals['_DIVREQUEST']._serialized_end=52
  _globals['_DIVREPLY']._serialized_start=54
  _globals['_DIVREPLY']._serialized_end=80
  _globals['_DIVSERVICE']._serialized_start=82
  _globals['_DIVSERVICE']._serialized_end=135
# @@protoc_insertion_point(module_scope)
